"""upgrade notifications table

Revision ID: 0143e6ac9aa7
Revises: 188e2b645ef6
Create Date: 2026-06-09 19:40:22.304560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0143e6ac9aa7'
down_revision = '188e2b645ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('recipient_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dispatch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'dispatches', ['dispatch_id'], ['id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.drop_column('message')
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('content')
        batch_op.drop_column('status')
        batch_op.drop_column('order_id')
        batch_op.drop_column('dispatch_id')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
