"""add group_id to orders

Revision ID: 188e2b645ef6
Revises: 4189720aa353
Create Date: 2026-06-09 19:28:26.140741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188e2b645ef6'
down_revision = '4189720aa353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_group_id'))
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
