"""add deposit_balance to orders

Revision ID: 4189720aa353
Revises: 534a267a7a66
Create Date: 2026-06-09 12:55:00.088867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4189720aa353'
down_revision = '534a267a7a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_amount', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('balance_amount', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('balance_amount')
        batch_op.drop_column('deposit_amount')

    # ### end Alembic commands ###
