"""rebuild notifications and add driver line bind

Revision ID: 4639baa82115
Revises: 0143e6ac9aa7
Create Date: 2026-06-09 19:47:16.760270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4639baa82115'
down_revision = '0143e6ac9aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_line_bound', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('bound_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('receiver_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('receiver_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('receiver_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.drop_column('notification_type')
        batch_op.drop_column('content')
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recipient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('message')
        batch_op.drop_column('receiver_name')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('receiver_type')
        batch_op.drop_column('type')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('bound_at')
        batch_op.drop_column('is_line_bound')

    # ### end Alembic commands ###
