"""add line_user_id display_name to orders

Revision ID: 514283b25e63
Revises: f54e3af8198d
Create Date: 2026-06-09 01:53:11.986488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514283b25e63'
down_revision = 'f54e3af8198d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_user_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_line_user_id'), ['line_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_line_user_id'))
        batch_op.drop_column('display_name')
        batch_op.drop_column('line_user_id')

    # ### end Alembic commands ###
