"""add display_name to admins

Revision ID: 534a267a7a66
Revises: 0cea5721016a
Create Date: 2026-06-09 08:05:32.624573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534a267a7a66'
down_revision = '0cea5721016a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
