"""add full_payment receipt type and amount breakdown fields

Revision ID: a3e21d586af3
Revises: ac457e70c434
Create Date: 2026-06-14 01:35:31.034487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e21d586af3'
down_revision = 'ac457e70c434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balance_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('total_amount')
        batch_op.drop_column('balance_amount')
        batch_op.drop_column('deposit_amount')

    # ### end Alembic commands ###
