"""add_payment_source_and_fields_to_payments

Revision ID: a57c321985d9
Revises: cf95cf977880
Create Date: 2026-06-12 12:37:01.703469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57c321985d9'
down_revision = 'cf95cf977880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_source', sa.String(length=30), nullable=False, server_default='bank_transfer_report'))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('confirmed_by')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('amount')
        batch_op.drop_column('payment_source')

    # ### end Alembic commands ###
