"""add_vehicle_type_to_orders

Revision ID: cf95cf977880
Revises: f7f9ced00dd5
Create Date: 2026-06-12 00:16:38.371232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf95cf977880'
down_revision = 'f7f9ced00dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.String(length=20), nullable=False, server_default='minibus'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###
