"""add_announcement_fields

Revision ID: f7f9ced00dd5
Revises: 4639baa82115
Create Date: 2026-06-09 21:56:33.663330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f9ced00dd5'
down_revision = '4639baa82115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement_type', sa.String(length=20), nullable=False, server_default='一般公告'))
        batch_op.add_column(sa.Column('status',            sa.String(length=20), nullable=False, server_default='草稿'))
        batch_op.add_column(sa.Column('is_pinned',         sa.Boolean(),         nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('publish_to_line',   sa.Boolean(),         nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('line_target',       sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('updated_at',        sa.DateTime(),        nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('line_target')
        batch_op.drop_column('publish_to_line')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('status')
        batch_op.drop_column('announcement_type')

    # ### end Alembic commands ###
